#given an array of length n
#find the contiguous subarray(including empty subarray) which has the largets sum and return its sum
#sum of empty subarray is 0
#if all numbers are negative, return 0 which is the sum of empty subarray

#for every single subarray generated by the two loops, we calculate its sum using the sum function which takes O(n) time as it has to iterate through the subarray
#thus the overall time complexity is O(n^3)

def max_subarray_sum(arr):
    max_sum=0
    
    for j in range(len(arr)):
        for i in range(len(arr)+1):
            if i>=j:
                max_sum=max(max_sum,sum(arr[j:i]))
    return max_sum

#if the subarray is not allowed to be empty return the largest subarray sum which is the largest number in the array which has all negative numbers
#time complexity is still O(n^3)
def max_subarray_sum_non_empty(arr):
    arr1=sorted(arr)
    max_sum=arr1[len(arr)-1]
    
    for j in range(len(arr)):
        for i in range(len(arr)+1):
            if i>=j:
                max_sum=max(max_sum,sum(arr[j:i]))
    
    return max_sum  

#optimized approach using kadane's algorithm
#if all elements are negative, return 0
#time complexity is O(n)
def max_subarray_sum_kadane(arr):
    max_sum=0
    current_sum=0
    
    for num in arr:
        current_sum+=num
        if current_sum<0:
            current_sum=0
        max_sum=max(max_sum,current_sum)
    
    return max_sum
